#!/bin/bash
# chkconfig: 345 20 80
# description: Wanted start/shutdown script
# processname: wanted
#
# Installation:
# copy file to /etc/init.d
# chmod +x /etc/init.d/wanted
# chkconfig --add /etc/init.d/wanted
# chkconfig play on
#
# Usage: (as root)
# service wanted start
# service wanted stop
# service wanted status
#
# Remember, you need python 2.6 to run the play command, it doesn't come standard with RedHat/Centos 5.5
# Also, you may want to temporarily remove the >/dev/null for debugging purposes

# User running the Play process
USER=pwanted

# Path to the application
APPLICATION_PATH=/opt/solong/wanted/prod/bin/
APPLICATION_MODE=prod

# source function library
. /lib/lsb/init-functions
RETVAL=0

start() {
  echo -n "Starting Play service: "
  su -s /bin/sh $USER -c "/opt/solong/wanted/prod/bin/wanted -Dhttp.address=127.0.0.1 -Dhttp.=9000 -Dconfig.file=/opt/solong/wanted/prod/conf/application.conf"
  RETVAL=$?

  if [ $RETVAL -eq 0 ]; then
    echo_success
  else
    echo_failure
  fi
  echo
}
stop() {
  echo -n "Shutting down Play service: "
  kill -15 $(cat /opt/solong/wanted/prod/RUNNING_PID)

  RETVAL=$?

  if [ $RETVAL -eq 0 ]; then
    echo_success
  else
    echo_failure
  fi
  echo
}
status() {
  #${PLAY} status ${APPLICATION_PATH}
  #${PLAY} status ${APPLICATION2_PATH}
  #RETVAL=$?
  echo "NOT IMPLEMENTED YET"
}
clean() {
        #rm -f ${APPLICATION_PATH}/server.pid
        #rm -f ${APPLICATION2_PATH}/service.pid
        echo "NOT IMPLEMENTED YET"
}
case "$1" in
  start)
  clean
  start
  ;;
  stop)
  stop
  ;;
  restart|reload)
  stop
  sleep 10
  start
  ;;
  status)
  status
  ;;
  clean)
  clean
  ;;
  *)
  echo "Usage: $0 {start|stop|restart|status}"
esac
exit 0
